name: ZeroWastePantry
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  firebase_database: ^12.0.4
  firebase_storage: ^13.0.4
  flutter_local_notifications: ^19.5.0
  intl: ^0.20.2
  cupertino_icons: ^1.0.8
  google_sign_in: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  
flutter:
  uses-material-design: true
  assets:
    - assets/images/zerowaste_logo.png
    - assets/images/google.png
